server:
  port: 8081
## dubbo服务端口，我们无需知道dubbo服务运行在哪个端口，也可以将其设为随机端口 -1
dubbo:
  protocol:
    port: 20008
  application:
    name: dubbo-provider
# dubbo服务所在包路径
  scan:
    base-packages: com.lontyu.dubbo.provider.service
  registry:
    address: zookeeper://127.0.0.1:2181
#设置服务的日志输出级别为debug级
logging:
  level:
    com.lontyu.dubbo.provider.service: info
